export const projects = [
  {
    title: "AI Journal App",
    subtitle: {
      fr: "Application de journalisation full-stack sur la stack MERN avec authentification JWT via Supabase. Intègre l'IA pour l'analyse des sentiments, l'extraction de thèmes et le résumé des entrées.",
      en: "Full-stack AI journaling app on the MERN stack with Supabase-backed JWT authentication. Integrated LLM-powered sentiment analysis, theme extraction, and entry summarization for actionable writing insights.",
    },
    technologies: ["React", "Node.js", "MongoDB", "Express.js", "Supabase", "JWT", "Tailwind CSS", "Radix UI", "Zustand"],
    path: "https://ai-journaling.onrender.com/",
    git: "",
    img: "ai-journal",
    category: "fullstack",
    featured: true,
  },
  {
    title: "Expense Wallet App",
    subtitle: {
      fr: "Application de finance personnelle cross-platform avec React Native (Expo) et un backend Node.js/Express. Intègre Clerk pour l'authentification, avec un tableau de bord en temps réel des dépenses.",
      en: "Cross-platform personal finance app with React Native (Expo) and a Node.js/Express backend. Integrated Clerk for end-to-end auth and role-based access. Real-time spending dashboard optimized for iOS, Android, and web.",
    },
    technologies: ["React Native", "Expo", "Node.js", "Express.js", "Clerk", "JWT", "Tailwind CSS"],
    path: "",
    git: "https://github.com/gup-abhi/expense-wallet-frontend",
    img: "expense-wallet",
    category: "fullstack",
    featured: true,
  },
  {
    title: "Relationship Dashboard",
    subtitle: {
      fr: "Application web full-stack qui analyse les discussions sur les relations depuis des forums en ligne via NLP et n8n. Fournit des insights sur les tendances, problèmes courants et sentiments.",
      en: "Full-stack web app that provides NLP-powered insights from relationship-related online forum discussions. Built with n8n automation and Gemini API for sentiment analysis and trend visualization.",
    },
    technologies: ["n8n", "Gemini API", "Next.js", "React", "Node.js", "MongoDB", "TypeScript", "Recharts", "Zustand"],
    path: "https://relationship-dashboard.abhishek-gupta.tech/",
    git: "",
    img: "relationship-dashboard",
    category: "fullstack",
    featured: true,
  },
  {
    title: "Chat App",
    subtitle: {
      fr: "Plateforme de chat en temps réel avec React (Vite), Socket.IO, Express.js et MongoDB. Supporte la messagerie instantanée, la présence en ligne et le partage de médias avec JWT et Cloudinary.",
      en: "Real-time chat platform built with React (Vite), Socket.IO, Express.js, and MongoDB. Supports live messaging, online presence tracking, and media uploads with JWT auth and Cloudinary for avatar storage.",
    },
    technologies: ["React", "Vite", "Socket.IO", "Express.js", "MongoDB", "JWT", "Cloudinary", "Tailwind CSS", "Zustand"],
    path: "https://chat-app-7ruk.onrender.com/",
    git: "",
    img: "chat-app",
    category: "fullstack",
    featured: true,
  },
  {
    title: "Expense Tracker",
    subtitle: {
      fr: "Application complète de gestion des dépenses sur la stack PERN (PostgreSQL, Express.js, React.js, Node.js). Authentification, tableau de bord interactif et rapports financiers détaillés.",
      en: "Comprehensive expense tracking app on the PERN stack (PostgreSQL, Express.js, React.js, Node.js). Features user authentication, an interactive dashboard, and detailed financial reports with Chart.js.",
    },
    technologies: ["React", "PostgreSQL", "Express.js", "Node.js", "JWT", "Chart.js"],
    path: "http://expense-tracker.abhishek-gupta.tech/",
    git: "https://github.com/gup-abhi/expense-tracker-server",
    img: "expense",
    category: "fullstack",
    featured: false,
  },
  {
    title: "Top 250 Movies",
    subtitle: {
      fr: "Application web affichant les 250 meilleurs films selon l'IMDB, avec recherche, filtres et informations détaillées. Développée avec React et intégration d'une API externe.",
      en: "Web application displaying the top 250 IMDB-rated movies with search, filters, and detailed movie info. Built with React and external API integration.",
    },
    technologies: ["React", "JavaScript", "CSS", "API Integration"],
    path: "https://top-250-movies.onrender.com/",
    git: "",
    img: "top-movies",
    category: "frontend",
    featured: false,
  },
];
